development: &common_settings
  cluster_name: "[cluster-name]"
  dashboard_url: "/pun/dev/[app-name]"
  file_app_url: "/pun/sys/files/fs"
  file_editor_url: "/pun/sys/file-editor/edit"
  home_page: "https://hprc.tamu.edu"
  modules_db_path: "/sw/hprc/sw/dor-hprc-tools-dashboard-utils/bin/"
  driver_scripts_path: "/var/www/ood/apps/dev/u.os309860/gateway/dor-hprc-drona-composer/machine_driver_scripts"
  default_python_venv: "/sw/hprc/sw/Python/virtualenvs/Python/3.8.6/default_dashboard_python-env/"
  env_repo_github: "https://github.com/tamu-edu/dor-hprc-drona-environments.git"

production:
  <<: *common_settings
  dashboard_url: "/pun/sys/dor-hprc-drona-composer"
  driver_scripts_path: "/var/www/ood/apps/sys/dor-hprc-drona-composer/machine_driver_scripts"
  env_repo_github: "https://github.com/tamu-edu/dor-hprc-drona-environments.git"
